services:
  # Flask Application
  flask_app:
    build: .
    image: int_map-img
    container_name: int_map-cnt 
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FLASK_APP=app.py
      - FLASK_DEBUG=1         # Enable debug mode
      - PYTHONUNBUFFERED=1    # Force logs to show immediately

  # Ollama Service
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama_mario-cnt
    ports:
      - "11434:11434"
    volumes:
      - ~/ollama_models:/root/.ollama
      - ./Modelfile:/root/Modelfile
      - ./init-ollama.sh:/root/init-ollama.sh
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

# Volumes for persistent data
volumes:
  ollama_models:
