services:
  # Flask Application
  flask_app:
    build: .
    image: int_map-img
    container_name: int_map-cnt 
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - FLASK_APP=app.py
      - FLASK_DEBUG=1         # Enable debug mode
      - PYTHONUNBUFFERED=1    # Force logs to show immediately
      - FLASK_ENV=development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Ollama Service
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama_mario-cnt
    ports:
      - "11434:11434"
    volumes:
      - ~/ollama_models:/root/.ollama
      - ./Modelfile:/root/Modelfile
      - ./init-ollama.sh:/root/init-ollama.sh
    command: serve
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags | grep -q mario || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 180s

networks:
  app_network:
    driver: bridge

volumes:
  ollama_models:
